version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - add_ssh_keys
      - run:
          name: Start SSH agent
          command: eval $(ssh-agent -s); ssh-add ~/.ssh/id_rsa_*; sleep 10
      - deploy:
          name: Deploy
          command: DEBUG=* node ./node_modules/.bin/git-deploy push .git-deploy/config.json
